### ISSUE TITLE
Create repository to frontend tests

### ISSUE THREAD

**Issue by teseu** [lucasmauricio/arrakis#5]
A frontend to host tests to all services
* named after a Dune planet (like all repos)
* php
* simple, it has only the necessary code to work

**Comment by lucasmauricio** [comment]
Basic operations test app must do:

Description| Rest Operation
--------------| ---------------------
List all items| GET / 
Get a identified item| GET /{id}
Create a new item| POST /
Edit item data| PUT /{id}
Delete item| DELETE /{id}

**Comment by teseu** [comment]
Well, after our last discussion, I guess I've another name, more suitable for this new use we decide. Since it's for a test for all services, I think Kaitain, the new capital, with four moons, and everlasting good weather, is a better name.

I'll create some html code to initialize and plan some php to make this happen, when you create the repo I can upload there.

**Comment by lucasmauricio** [comment]
Repo created.
Check it out: https://github.com/lucasmauricio/kaitain
